---
- hosts: all
  become: true
  tasks:
  
  - name: Update Repository Index
    apt:
      update_cache: yes

  - name: Remove nginx package
    apt:
      name: nginx
      state: absent

  - name: Remove php support for Apache
    apt:
      name: libapache2-mod-php
      state: absent
